[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "smallir-dac"
version = "0.1.0"
description = "A soc tool for managing detection rules as code (DAC)"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "pyyaml>=6.0.3",
    "toml>=0.10.2"
]

[tool.hatch.build.targets.wheel]
packages = ["src/smallir"]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "isort>=8.0.1",
    "types-pyyaml>=6.0.12.20260724",
]
